name = "dvorak"
author = "Benjamin"
version = "1.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba09bb836b6b8707ababd6be788f75d97dd01e008072a5f6b13945f9f24fa8ff"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
